version: "2"
services:
  grpc:
    build: .
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
