apiVersion: v1
kind: Service
metadata:
  name: grpc
  labels:
    role: grpc
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    role: grpc
status:
  loadBalancer: {}
