apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: warhammer
namespace: warhammer
resources:
  - db-deployment.yaml
  - grpc-deployment.yaml
  - grpc-service.yaml
  - db-pvc.yaml
  - db-config.yaml
